edition = "2021"

# We are going to enable these after switching to nightly tool chain
binop_separator = "Front"
format_strings = true
max_width = 120
comment_width = 120
merge_derives = false
reorder_imports = true
use_field_init_shorthand = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
newline_style = "Unix"
trailing_comma = "Vertical"
use_small_heuristics = "Max"
